export const NOTIFIER_ENVIRONMENT = {
  TABLE_NAME: "TABLE_NAME",
  WEB_PUSH_PUBLIC_KEY: "WEB_PUSH_PUBLIC_KEY",
  WEB_PUSH_PRIVATE_KEY_PARAMETER: "WEB_PUSH_PRIVATE_KEY_PARAMETER",
  VAPID_SUBJECT: "VAPID_SUBJECT",
} as const;
